version: '3.8'

services:
    db:
        image: postgres:16.2
        restart: always
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        container_name: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:${DB_PORT}'

    app:
        build:
            context: .
            dockerfile: Dockerfile.${ENV}
        container_name: todo-api
        environment:
            - PORT=${PORT}
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - db
        volumes:
            - ./src:/app/src

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
        ports:
            - '${PG_ADMIN_PORT}:80'
        depends_on:
            - db
        volumes:
            - pgadmin:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin:
